# Generated by Django 4.2.30 on 2026-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('report_type', models.CharField(default='gas', max_length=20)),
                ('reference_id', models.CharField(blank=True, default='', max_length=200)),
                ('property_address', models.CharField(blank=True, default='', max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('pdf_url', models.CharField(blank=True, default='', max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
